name: 
fillType: 
type: 
userCanEditContent: #only for Registry filltype
ttl: 
maxSize: 
typicalSize: 
fields:
    - complex_key:
          compositeFields:
              - 
              - 
          index: true
          nullable: false
          primaryKey: true
          type: composite
          unique: true
    - _:
          primaryKey: 
          index: 
          nullable: 
          type: 
          unique: 
defaults: []
        